fail-on-scopes:
  - runtime

fail-on-severity:
  - critical
  - high

allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD

deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0

comment-summary-in-pr: always

base-ref: main
head-ref: ${{ github.head_ref }}
