repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(ts|js|json|md|yml|yaml)$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(ts|js)$
        additional_dependencies:
          - eslint@9.27.0
          - "@typescript-eslint/eslint-plugin@8.32.1"
          - "@typescript-eslint/parser@8.32.1"

  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type checking
        entry: npm run type-check
        language: node
        files: \.(ts)$
        pass_filenames: false

      - id: jest-tests
        name: Jest unit tests
        entry: npm test
        language: node
        files: \.(ts)$
        pass_filenames: false
